#!/usr/bin/env bash

# bspwm directory
DIR="$HOME/.config/bspwm"
CONFIG="$HOME/.config/polybar/"

# fix padding
bspc config bottom_padding 0
bspc config top_padding 0

# launch polybar
#bash "$DIR"/themes/polybar.sh
bash "$CONFIG"/polybar.sh
