#!/usr/bin/env bash

color=$(xcolor --format hex --preview-size 255 --scale 10)
image=/tmp/${color}.png

main() {
    if [[ "$color" ]]; then
        echo $color | tr -d "\n" | xclip -selection clipboard
        convert -size 48x48 xc:"$color" ${image}
        dunstify -u low -h string:x-dunst-stack-tag:obcolorpicker -i ${image} "$color, copied to clipboard."
    fi
}

main
