#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## Run ncmpcpp with alternate config

# kitty directory
DIR="$HOME/.config/kitty"

CONFIG="$DIR/kitty.conf"

kitty --class 'Music,Music' --config "$CONFIG" \
		  -o window.dimensions.columns=109 window.dimensions.lines=22 \
		  -e ~/.config/ncmpcpp/scripts/ncmpcpp-art

