#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/rofi"
STYLE="default"
RASI="$DIR/windows.rasi"

# Run
rofi \
    -show window \
	-theme ${RASI}
