#!/usr/bin/env bash

DIR="$HOME/.config/rofi"
RASI="$DIR/asroot.rasi"

prompt='Root'
mesg="Run Applications As Root"
term="kitty --class kitty-float --config $HOME/.config/kitty/kitty.conf"

layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
    option_1=" Kitty"
    option_2=" Thunar"
    option_3=" VSCode"
    option_4=" MC"
    option_5=" Nvim"
else
    option_1=""
    option_2=""
    option_3=""
    option_4=""
    option_5=""
fi

rofi_cmd() {
    rofi -dmenu \
        -p "$prompt" \
        -mesg "$mesg" \
        -markup-rows \
        -theme ${RASI}
}

run_rofi() {
    echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

run_cmd() {
    if [[ "$1" == '--opt1' ]]; then
        bspasroot "$term"
    elif [[ "$1" == '--opt2' ]]; then
        bspasroot 'dbus-run-session thunar'
    elif [[ "$1" == '--opt3' ]]; then
        bspasroot code
    elif [[ "$1" == '--opt4' ]]; then
        bspasroot "$term -e mc"
    elif [[ "$1" == '--opt5' ]]; then
        bspasroot "$term -e nvim"
    fi
}

chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
        run_cmd --opt1
        ;;
    $option_2)
        run_cmd --opt2
        ;;
    $option_3)
        run_cmd --opt3
        ;;
    $option_4)
        run_cmd --opt4
        ;;
    $option_5)
        run_cmd --opt5
        ;;
esac
